### ISSUE TITLE
不行啊老哥 

### ISSUE THREAD

**Issue by shen-lan** [maixiaojie/git-emoji-zh#1]
提交上去后显示：

:bug:修改 logo

图标变成了 字符

**Comment by shen-lan** [comment]
？？？？？？卧槽？？？是因为我是gitlab ???

**Comment by maixiaojie** [comment]
是不是gitlab版本的问题，不支持emoji

**Comment by 2234839** [comment]
后面需要一个空格

**Comment by maixiaojie** [comment]
@shen-lan 是的，也可能是因为少了一个空格，你可以先使用英文版的（git-emoji）。中文版的 @2234839 已经提了pr，我会抽时间发布新版本。

**Comment by maixiaojie** [comment]
@shen-lan 已经更新为原生的 emoji. 可以体验一下，有问题咱们继续讨论 👍
