### ISSUE TITLE
建议可以切换使用 :标签: 或者纯emoji

### ISSUE THREAD

**Issue by 2234839** [maixiaojie/git-emoji-zh#12]
因为emoji本身实际意思没有标签精确，他丢失了这方面的信息，例如一个没接触过emoji的他看到这些会很懵逼，但原来的标签当他将鼠标移到提交信息上时还是可以看到标签本来的单词的

**Comment by maixiaojie** [comment]
这个不知道好不好弄，待我看下。如果有好的解决方案，可以pr

**Comment by maixiaojie** [comment]
@2234839  已经发布了新版本
