### ISSUE TITLE
可不可以新增一个图标用于标记UI样式上的更新

### ISSUE THREAD

**Issue by MiracleRo** [maixiaojie/git-emoji-zh#15]
可不可以新增一个图标用于标记UI样式上的更新

**Comment by maixiaojie** [comment]
可以的 @MiracleRo

**Comment by maixiaojie** [comment]
@MiracleRo  已经发布了新版本

**Comment by MiracleRo** [comment]
十分感谢





------------------ 原始邮件 ------------------
发件人: 麦晓杰 lavna <notifications@github.com&gt;
发送时间: 2019年12月4日 16:15
收件人: maixiaojie/git-emoji-zh <git-emoji-zh@noreply.github.com&gt;
抄送: Ronaldo Lee <741556866@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[maixiaojie/git-emoji-zh] 可不可以新增一个图标用于标记UI样式上的更新 (#15)




@MiracleRo  已经发布了新版本
