### ISSUE TITLE
希望扩展一下图标数量

### ISSUE THREAD

**Issue by iWangJiaxiang** [maixiaojie/git-emoji-zh#18]
建议把 gitemoji加到插件里~ 

[gitmoji | An emoji guide for your commit messages](https://gitmoji.carloscuesta.me/)

**Comment by maixiaojie** [comment]
我们英文版目前是支持这些图标的哈，可以关注下。

https://github.com/maixiaojie/git-emoji

**Comment by iWangJiaxiang** [comment]
3q
