### ISSUE TITLE
讨论：使用原生emoji符号

### ISSUE THREAD

**Issue by nieheyong** [maixiaojie/git-emoji-zh#3]
原生emoji支持度更广，git-gmoji 最终输出的形如`:bug:`,在命令行中 git log 看到的也是纯文本，但是命令行支持原生emoji。
像这个项目 https://github.com/ahmadawais/Emoji-Log ，就使用的是原生的emoji

**Comment by maixiaojie** [comment]
@nieheyong  是个挺不错的想法，我也会去参考的。如果有好的实现思路，可以pr一波😁

**Comment by nieheyong** [comment]
@maixiaojie 实现起来的话很简单，对着你的代码修改一下，可是改了就不是git-emoji的标准了，或许你新开一个库叫Emoji-Log？

**Comment by maixiaojie** [comment]
@nieheyong  是的，我今天看了实现方法，也比较好改，但是原生的emoji会在不同的操作系统会有不同的表现。

**Comment by nieheyong** [comment]
@maixiaojie 虽然不同的操作系统不一样，但是大体意思是一样的。你的插件使用起来非常方便，但是用了git-emoji一段时间发现图标是在太多了，可选的太多反而很麻烦。感觉这个Emoji-Log 不多不少刚刚好

**Comment by maixiaojie** [comment]
@nieheyong  可以，精选一些常用的图标，或者可以自己配置

**Comment by maixiaojie** [comment]
@nieheyong 插件已经更新了，使用了原生的 emoji ,可以体验体验，有啥问题咱们继续讨论 👍

**Comment by nieheyong** [comment]
@maixiaojie  优秀 👍
